name: Snake Game

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Generate Snake Game
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: jovigod888
        run: |
          git clone https://github.com/Platane/snk.git
          cd snk
          python main.py --username $USERNAME --token $GITHUB_TOKEN
          cd..
          rm -rf snk

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: snake.svg
