name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar arquivos da cobrinha com Fundo Branco
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Força o fundo branco usando a paleta clara padrão do GitHub
            dist/snake.svg?palette=github-light
            dist/snake-dark.svg?palette=github-light

      - name: Deploy para branch snake-output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan snake-output
          git rm -rf .
          cp dist/snake.svg .
          cp dist/snake-dark.svg .
          git add snake.svg snake-dark.svg
          git commit -m "update snake animation with white background"
          git push origin snake-output --force
